### PR TITLE
Restructure + LINQ use in CommonController

### PR DESCRIPTION
**Pull request by dongle-the-gadget**
# Summary
- Database restructure
- Use LINQ to get intersection between user's guilds and bot's guilds.

### CODE REVIEW

**Review by itsWindows11 — DISMISSED** [review]
job

**Review by SapphireDisD — DISMISSED** [review]
I did a quick review and seems fine

**Comment by dongle-the-gadget** [comment]
@SapphireDisD, can you do a real world simulation test with the website to make sure that stuff works fine?

**Comment by SapphireDisD** [comment]
I forgot, let's see...

**Comment by dongle-the-gadget** [comment]
> I forgot, let's see...
Oh alright. I appreciate it though.

**Comment by itsWindows11** [comment]
Should we merge the changes?

**Comment by SapphireDisD** [comment]
Not yet

**Comment by dongle-the-gadget** [comment]
> Should we merge the changes?

Well I'd like to see a  test with the website because I'm not very certain of using `IEnumerable<JToken>` instead of `JArray`

**Comment by SapphireDisD** [comment]
Yeah it's broken. The issue fixed in Oops x2

**Comment by SapphireDisD** [comment]
I will do something...

**Comment by dongle-the-gadget** [comment]
> Yeah it's broken. The issue fixed in Oops x2

Oh okay.

**Comment by SapphireDisD** [comment]
Oh great i created a conflict lol

**Comment by dongle-the-gadget** [comment]
I'll resolve it

**Comment by itsWindows11** [comment]
> Oh great i created a conflict lol

You shouldn't have committed this LOL

**Comment by SapphireDisD** [comment]
Leaderboard doesn't load

**Comment by dongle-the-gadget** [comment]
> > Oh great i created a conflict lol
> 
> You shouldn't have committed this LOL

No worries, it got resolved.

**Comment by SapphireDisD** [comment]
NEVERMIND

**Comment by SapphireDisD** [comment]
I was in the wrong page

**Comment by dongle-the-gadget** [comment]
> I was in the wrong page

LOL

**Comment by SapphireDisD** [comment]
Though servers list and style changer are broken

**Comment by dongle-the-gadget** [comment]
Oh a failed check

**Comment by dongle-the-gadget** [comment]
StyleController is broken

**Comment by SapphireDisD** [comment]
Style fixed, but guilds list still broken

**Comment by dongle-the-gadget** [comment]
I guess it's due to me using `IEnumerable<JToken>`, but currently I don't have time to fix that. I guess I will come back in 2 hours.

**Comment by SapphireDisD** [comment]
I will change it for you

**Comment by itsWindows11** [comment]
Another failed check

**Comment by SapphireDisD** [comment]
It's JArray

**Comment by SapphireDisD** [comment]
Found the issue! Intersect with array of objects isn't a good idea. Changing back to previous code.

**Review by SapphireDisD — APPROVED** [review]
Now tested and working

**Comment by dongle-the-gadget** [comment]
Well since sap modified it so LINQ is not used so I removed that. I will just add that later.

**Pull request merged**
